### ISSUE TITLE
[3.0.0-alpha.4] TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by glen-84** [BigstickCarpet/swagger-parser#13]
I'm using dereference and calling `JSON.stringify` with the output (api), and I get the following error:

    D:\Programming\Projects\x\temprepo\gulpfile.js:10
                fs.writeFileSync("swagger.json", JSON.stringify(api, null, 4));
                                                      ^
    TypeError: Converting circular structure to JSON
        at Object.stringify (native)
        at D:\Programming\Projects\x\temprepo\gulpfile.js:10:51
        at Immediate.invokeCallback [as _onImmediate] (D:\Programming\Projects\x\temprepo\node_modules\swagger-parser\node_modules\json-schema-ref-parser\lib\util.js:41:14)

        at processImmediate [as _immediateCallback] (timers.js:367:17)

The file looks something like this:

```yaml
NewsArticle:
    title: NewsArticle
    type: object
    properties:
        id:
            type: integer
            format: int32
            x-mysql-type: int(11)
NewsArticleExt: # tmp
    title: NewsArticleExt
    type: object
    allOf:
        - $ref: "#/NewsArticle"
        - properties:
            test:
                type: string
```

Is it possible to resolve the local pointer by copying the content instead of referencing it? Or is there some other way of making this work?

**Comment by BigstickCarpet** [comment]
There are a few different answers to your question, but I suspect the one you care about is the first one.  :)

1. **There's a typo in your `$ref` pointer**
It looks like `#/NewsArticle` should actually be `#/definitions/NewsArticle`.  For example, [this Swagger file](https://gist.github.com/BigstickCarpet/09dd37c80d3324908ff0) dereferences without any circular references, so it can be serialized to JSON just fine.

2. **You found a bug in JSON Schema $Ref Parser**
Swagger Parser uses [JSON Schema $Ref Parser](https://github.com/BigstickCarpet/json-schema-ref-parser) to resolve & dereference `$ref` pointers.  In your example, `#/NewsArticle` is an invalid pointer, so it _should_ have thrown an error, but instead, JSON Schema $Ref Parser resolved it as `#/`.  Oops.  I'll get that fixed.

3. **The answer to your question is "Yes."**
You asked if there would be a way for Swagger Parser to dereference circular `$ref` pointers in such a way that it can be serialized to JSON.  That _is_ in the plan.  It won't be a perfect solution though, because there are _some_ circular references that simply cannot be serialized as JSON, but I'll do my best to make it work for anything I can.

**Comment by glen-84** [comment]
I forgot to mention that this is in a separate file, so it's not under the `definitions` key.

The structure is like this:

`swagger.yaml` includes:

```yaml
paths:
    # News
    /news/news-articles:
        $ref: "operations/news/news-articles.yaml#/NewsArticles"
```

`news-articles.yaml` includes:

```yaml
NewsArticles:
    get:
        summary: Get a list of articles
        tags:
            - News
        responses:
            200:
                description: Success
                schema:
                    type: array
                    items:
                        $ref: "../../definitions/models/news/news-article.yaml#/NewsArticleExt"
```

`news-article.yaml` includes what I showed in my first post above, so the pointer is internal within that file.

**Comment by BigstickCarpet** [comment]
Ok, this should be fixed now.  Update to `v3.0.0-alpha.5` and give it another try.

**Comment by glen-84** [comment]
Nice! It seems to work now. :smiley:

**Comment by BigstickCarpet** [comment]
Sweet.  Good to hear.  I'm still (slowly) going through all the unit tests to get them all passing.  In the meantime, feel free to open issues for any more bugs you find.
