### ISSUE TITLE
Make fs $refs relative to the same directory

### ISSUE THREAD

**Issue by christophercliff** [BigstickCarpet/swagger-parser#22]
I believe v2.5 resolved everything from the `swagger.yml` source directory or `process.cwd()`, but that appears to have changed after v3.

Is this configurable in v3?

To clarify, would prefer all references relative to a common base path, e.g. `/fruits/orange.yml` would use:

```yml
$ref: /fruits/apple.yml
$ref: /vegetables/carrot.yml
```

rather than:

```yml
$ref: ./apple.yml
$ref: ../vegetables/carrot.yml
```

**Comment by BigstickCarpet** [comment]
Unfortunately, there were several aspects of Swagger Parser 2.x that did not properly adhere to the specs.  One of the major changes in version 3.0 is that we now fully follow to the specs.  This ensures that Swagger Parser works consistently with other tools and libraries.

For JSON References, you can use absolute paths (e.g. `/vegetables/carrot.yml`), which will always be unambiguously resolved, or you can use relative paths (e.g. `../vegetables/carrot.yml`), which will be resolved relative to the current file path.

**Comment by christophercliff** [comment]
Are there any hooks in the API where I could override that?

**Comment by BigstickCarpet** [comment]
There aren't any API hooks, since the functionality is dictated by the spec.  But all the logic is in [`read.js`](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/lib/read.js), so you can fork and modify that one file.   Specifically, the methods you'd need to change are [`read$RefFile`](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/lib/read.js#L88-L130) (for local files) and [`read$RefUrl`](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/lib/read.js#L132-L159) for URLs.

**Comment by christophercliff** [comment]
Thanks.
