### ISSUE TITLE
Parser isn't allowing `x-` when it should be

### ISSUE THREAD

**Issue by Kegsay** [BigstickCarpet/swagger-parser#23]
The following file fails to validate (it works when using http://editor.swagger.io/ ):

```yaml
swagger: '2.0'
info:
  title: "MWE"
  version: "1.0.0"
host: localhost:8008
schemes:
  - https
basePath: /path
paths:
  "/thumbnail":
    get:
      summary: "Download a thumbnail"
      produces: ["image/jpeg", "image/png"]
      responses:
        200:
          description: "A thumbnail of the requested content."
          headers:
            Content-Type:
              description: "The content type of the thumbnail."
              x-example: "image/jpeg"
              type: "string"
              enum: ["image/jpeg", "image/png"]
          schema:
            type: file
```

```
{ [SyntaxError: Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths/~1thumbnail/get/responses/200
    Additional properties not allowed: x-example at #/paths/~1thumbnail/get/responses/200/headers/Content-Type
    Additional properties not allowed: schema,headers,description at #/paths/~1thumbnail/get/responses/200 
JSON_OBJECT_VALIDATION_FAILED] toJSON: [Function: errorToJSON] }
```

This uses a custom key `x-example` on the `Header Object`. This is valid swagger as per https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#headerObject

Removal of `x-example` makes the parser validate successfully. 

```
swagger-parser version: 3.2.1
```

**Comment by BigstickCarpet** [comment]
Thanks for pointing this out!  The problem is that the [official Swagger schema on npm](https://www.npmjs.com/package/swagger-schema-official) hasn't been updated in six months, so it's missing [several recent changes](https://github.com/swagger-api/swagger-spec/commits/master/schemas/v2.0/schema.json).  I've [opened an issue](https://github.com/swagger-api/swagger-spec/issues/335) on the Swagger Spec project asking them to update it.

In the meantime, I'll release a new version of Swagger Parser that has the updated schema.

**Comment by BigstickCarpet** [comment]
Good news!  They've updated [the npm package](https://www.npmjs.com/package/swagger-schema-official), so now it's all good.  Update to Swagger Parser `v3.3.0` and you should be good to go

**Comment by Kegsay** [comment]
Thank you as always for the quick response :D
