### ISSUE TITLE
Cannot Parse/Validate Any Yaml File

### ISSUE THREAD

**Issue by atom0s** [BigstickCarpet/swagger-parser#25]
Trying to parse/validate any yaml file results in the same error every time:
```SyntaxError: Unable to resolve $ref pointer "file:///C:/Users/atom0s/Desktop/test/swagger.yaml"(…)```

The file can contain anything in it, or be empty, no matter what I get this error. I'm attempting to parse on Windows 8.1.

The code I am testing with looks like this:
```javascript
    <script>
        SwaggerParser.validate('swagger.yaml').then(function(api) {
            console.log(api);
        }).catch(function(err) {
            console.error(err);
        });
    </script>
```

Here's an image of the error from the console:
![http://i.imgur.com/pU0Q9Pe.png](http://i.imgur.com/pU0Q9Pe.png)

**Comment by BigstickCarpet** [comment]
Hi.  Sorry for the delayed response.  I've been away on holiday for a few weeks.

Try referencing the file as `C:\Users\atom0s\Desktop\test\swagger.yaml` or as `C:/Users/atom0s/Desktop/test/swagger.yaml` rather than using the `file:///` protocol.  Swagger Parser doesn't currently support the `file://` protocol.

However, I don't see any reason _not_ to support this protocol, so I will add this functionality soon.  Or, if you want to submit a PR, I'll gladly review and merge it.  Pretty sure it'll just be a small change to [this line of code](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/lib/read.js#L100) (and a new unit test).
