### ISSUE TITLE
APIs.guru changed directory structure

### ISSUE THREAD

**Issue by IvanGoncharov** [BigstickCarpet/swagger-parser#26]
First of all thank you for using and promoting my project.
To fix APIs-guru/api-models/issues/19 I changed directory structure, so instead of top level all specs moved into [APIs](https://github.com/APIs-guru/api-models/tree/master/APIs) folder.
I also switched from JSON to YAML.

It breaks your test suite and I see 3 possibilities to fix it:
- Switch to using official [REST API](https://github.com/APIs-guru/api-models/blob/master/API.md). It also support CORS so could be used directly for browser tests.
- Use [gh-pages](https://github.com/APIs-guru/api-models/tree/gh-pages) branch which stay with the same directory structure and have JSON files.
- Adjust to new directory structure and YAML

When you make your decision I can assist with migration.

P.S. I also create a badge to show number of APIs in collection: https://apis-guru.github.io/api-models/apis_in_collection_banner.svg
Maybe you can use it in your README or have an idea about text that better suite this badge.

**Comment by BigstickCarpet** [comment]
Hi.  Sorry for not responding sooner.  Been crazy busy!

Thank you for exposing your Swagger files via a REST API.  That makes it SUPER easy for me to use them without having to create duplicate copies of them in this repo.  I've made the necessary code changes on my end to use your API, and it _mostly_ works great.  But there are a couple APIs that don't pass validation, which is causing my test suites to fail.  :(    Any chance you could fix these validation issues?

[**backupify.com**](http://bigstickcarpet.com/swagger-parser/www/index.html?url=https%3A%2F%2Fapis-guru.github.io%2Fapi-models%2Fbackupify.com%2F1.0.0%2Fswagger.yaml)
The `blob` definition on [line 1461](https://github.com/APIs-guru/api-models/blob/2178c3e9e42d56d27c7bd94baf1d65ef50927e8e/APIs/backupify.com/1.0.0/swagger.yaml#L1461-L1462) only has a `description` which isn't enough information to satisfy the [`oneOf` rule](https://github.com/swagger-api/swagger-spec/blob/dbb81f8dedc6af59f7adf4c132219639e018470d/schemas/v2.0/schema.json#L371-L378) in the Swagger 2.0 schema.  Adding `type: object` solves the problem:

```yaml
  blob:
    type: object
    description: A Binary Large OBject
```

[**motaword.com**](http://bigstickcarpet.com/swagger-parser/www/index.html?url=https%3A%2F%2Fapis-guru.github.io%2Fapi-models%2Fmotaword.com%2Falpha-0.1.0%2Fswagger.yaml)
The `POST /projects` endpoint has [`file` parameters](https://github.com/APIs-guru/api-models/blob/9963cc6ab2460ed4177ef1fa9ba076c67dacfff3/APIs/motaword.com/alpha-0.1.0/swagger.yaml#L151-L162).  According to the Swagger 2.0 spec, [if a parameter's `type` is `"file"`, the `consumes` MUST be either `"multipart/form-data"`, `"application/x-www-form-urlencoded"`, or both](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameter-object).  This can be fixed by adding the following at [line 126](https://github.com/APIs-guru/api-models/blob/9963cc6ab2460ed4177ef1fa9ba076c67dacfff3/APIs/motaword.com/alpha-0.1.0/swagger.yaml#L126):

```yaml
    post:
      description: Create a new project
      operationId: createProject
      consumes:
        - multipart/form-data
```

**Comment by IvanGoncharov** [comment]
#28 Solves all issues except last two.
I will look into them tomorrow

**Comment by BigstickCarpet** [comment]
Ah shit.  Didn't realize they had updated the schema.  I **really** wish they would use semver, so npm would keep Swagger Parser up-to-date automatically.  :(

Thanks for fixing that
