### ISSUE TITLE
Problem validating my swagger json file

### ISSUE THREAD

**Issue by nuruddeensalihu** [BigstickCarpet/swagger-parser#69]
Hi,

I have an existing apis [here ](https://developer-qa.ezypay.com/timeline-api) and [here ](https://developer-qa.ezypay.com/webhook-api) and i tried to validate it on  http://bigstickcarpet.com/swagger-parser/www/index.html# . The first api(i.e timeline) returns the error 

> Validation failed. /paths/v2/timelines/{entity}/{entityId}/get is missing path parameter(s) for {entity},{entityId}

.The problem is , the said parameters exist. However i am not sure where the error is coming from . Can you please elaborate how the validation works ? It recently noticed readme.io uses your tool for validations and it doesn't allow integration unless the validation pass.

**Comment by BigstickCarpet** [comment]
The API is failing validation because the `{entity}` and `{entityId}` parameters should be `in: path`, not `in: query`

**Comment by Ass7** [comment]
Hello , I'm trying to use swaggerize (node tool with yeoman) in order to scaffold a front tier layer with Angular-JS.
Yet having SAME error

`p077121@FRLH256527 bank-account-kata (ROO2-BOOT-VERSION)$yo swaggerize
Swaggerize Generator
Tell us a bit about your application
? Path (or URL) to swagger document: api-docs.json
? Path (or URL) to swagger document: api-docs.json
? Framework: (Use arrow keys)
? Framework: express
? What would you like to call this project: (bank-account-kata)
? What would you like to call this project: bank-account-kata
? Your name: gfds
? Your name: gfds
? Your github user name: gfds
? Your github user name: gfds
? Your email: gsdf
? Your email: gsdf
events.js:160
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Validation failed. /paths/api/accounttransactions/{accountTransaction}/get is missing path parameter(s) for {accountTransaction}
    at validatePathParameters (C:\Users\p077121\AppData\Roaming\npm\node_modules\generator-swaggerize\node_modules\swagger-parser\lib\validate-spec.js:174:15)
    at validateParameters (C:\Users\p077121\AppData\Roaming\npm\node_modules\generator-swaggerize\node_modules\swagger-parser\lib\validate-spec.js:99:3)
    at C:\Users\p077121\AppData\Roaming\npm\node_modules\generator-swaggerize\node_modules\swagger-parser\lib\validate-spec.js:45:7
    at Array.forEach (native)
    at validatePath (C:\Users\p077121\AppData\Roaming\npm\node_modules\generator-swaggerize\node_modules\swagger-parser\lib\validate-spec.js:40:18)
    at C:\Users\p077121\AppData\Roaming\npm\node_modules\generator-swaggerize\node_modules\swagger-parser\lib\validate-spec.js:25:7
    at Array.forEach (native)
    at validateSpec (C:\Users\p077121\AppData\Roaming\npm\node_modules\generator-swaggerize\node_modules\swagger-parser\lib\validate-spec.js:20:9)
    at C:\Users\p077121\AppData\Roaming\npm\node_modules\generator-swaggerize\node_modules\swagger-parser\lib\index.js:161:9
`

So my questiob is : is it possible to workaround ? HOW ? 

1/ get a correct json from swagger ?
2/ adapt the parsing feature of swaggerize ?

**Comment by BigstickCarpet** [comment]
@Ass7 - See my comment above for the solution.  You need to define a path parameter for `{accountTransaction}`.  For example:

```yaml
parameters:
  - name: accountTransaction
    in: path
    required: true
    type: string
```

**Comment by Ass7** [comment]
Hey @BigstickCarpet   thanks a lot for your kind answer (y) 
Yet I don't see where this yaml code can come, as I get the swagger json and ui generated from maven , by a Java spring-boot app...  

YES: I'm afraid its generated...not a by-the-middle approche, shall I say...sorry :/

Maybe there's just no adapted workaround though...

**Comment by BigstickCarpet** [comment]
Ah, ok.  Well in that case then, your only option may be to disable Swagger Parser's validator.  You can do that in [the options parameter](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/options.md), like this:

```javascript
SwaggerParser.dereference("my-api.yaml", { validate: { spec: false }});
```
