### ISSUE TITLE
README: Basic Example is misleading/wrong

### ISSUE THREAD

**Issue by Kegsay** [BigstickCarpet/swagger-parser#7]
The basic example in the README file is referencing a function `swagger.parser.parse` but it should really be `parser.parse` as described further down. It would also be nice to have the one line `require` call as well, since referencing variables which aren't declared in an example without comments needlessly obfuscates things.

The section "The API" is also referring to `swagger` when it really means `swaggerPath`.

**Comment by BigstickCarpet** [comment]
Hmmm... I see the potential problem there, but I'm not sure the best way to address it.  My intent with the "basic example" is to show a short code snippet that demonstrates the basic usage of Swagger Parser regardless of whether you're using it via Node, Bower, or AMD.  That's why it doesn't include a `require()` call.   In the next section, I show code samples that are specific to Node, Bower, and AMD.

Maybe I should just delete the "basic example" section altogether, and show a full code sample in each of the Node, Bower, and AMD sections instead.   What do you think?

**Comment by Kegsay** [comment]
> Maybe I should just delete the "basic example" section altogether, and show a full code sample in each of the Node, Bower, and AMD sections instead. What do you think?

I think this sounds sensible, as it will be correct for the given platform/framework rather than being a generalised example which doesn't quite work for any. The API just isn't complicated enough to warrant a single generalised version to save space. It wouldn't be as big of a problem if it weren't so prominent as it is the very first code snippet indicating how to use it. From what I have seen though, this is one of the best Swagger 2.0 validators I've come across.

**Comment by BigstickCarpet** [comment]
Done!
