### ISSUE TITLE
Swagger definition is modified by validator

### ISSUE THREAD

**Issue by alasdairhurst** [BigstickCarpet/swagger-parser#77]
From the look of things, the validate function dereferences the swagger too. This cannot be disabled, and it modifies the original definition that was passed in. Ideally validate should not be mutating anything.

1. If mutation is necesarry, the new swagger should be returned with the validation result
2. dereferencing should be optional. I just want to make sure that my swagger definition is valid. I don't want a new one.

**Comment by BigstickCarpet** [comment]
The `validate()` method has always called `dereference()` internally.  That behavior is [documented here](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/swagger-parser.md#validateapi-options-callback).  This is necessary because the JSON schema validator isn't able to resolve `$ref` pointers or handle circular references.

If you pass-in an object instead of a URL, then Swagger-Parser will directly mutate that object. If you want to keep a copy of the original object, then you'll need to do a [deep clone](https://lodash.com/docs/4.17.4#cloneDeep) before passing it to Swagger-Parser.

**Comment by alasdairhurst** [comment]
Yup, cloning the object was my personal fix for this. Didn't notice that part of the documentation though, thanks. It's still a little unexpected though.
