### ISSUE TITLE
Publish a new release to NPM?

### ISSUE THREAD

**Issue by JamesMGreene** [BigstickCarpet/swagger-parser#85]
You updated your dependencies in the "package.json" file:
https://github.com/BigstickCarpet/swagger-parser/commit/2403ab25965bc9ab43378e0386f5c5969b9faf67#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Most importantly, I am interested in your fix to `json-schema-ref-parser`:
https://github.com/BigstickCarpet/json-schema-ref-parser/commit/24ca937b61d825e09cf31a028140bc98e196c4a0

Thank you! 🙏

**Comment by BigstickCarpet** [comment]
I'll publish a new release to NPM ASAP, probably within the next couple of days.  I just need to [fix the build](https://travis-ci.org/BigstickCarpet/swagger-parser) first.  I'm working on it.

**Comment by JamesMGreene** [comment]
:+1:

**Comment by marcelstoer** [comment]
#84 would have to be merged first so that tests don't fail anymore.

**Comment by realityking** [comment]
@BigstickCarpet anything I can do to help to get this out?

**Comment by BigstickCarpet** [comment]
Sorry guys.  I was away for a while due to an unexpected family emergency.  I'm back now.

I'm _almost_ ready to publish a new release.  I've finished merging @marcelstoer's PRs and fixing a bunch of tests that were causing the build to fail.  All tests pass on Node now.  But [**some tests are still failing in web browsers**](http://bigstickcarpet.com/swagger-parser/test/index.html?grep=specification%20validation).  If one of you wants to take a look at those tests and maybe submit a PR, I'd really appreciate it.  Otherwise, I'll try to look at them tomorrow.

**Comment by BigstickCarpet** [comment]
Good news!  All tests are now passing.  [Version 4.1.0 has been released!](https://github.com/BigstickCarpet/swagger-parser/blob/master/CHANGELOG.md)
